import "./globals.css";
import localFont from 'next/font/local'

const montserrat = localFont({
  src: [
    {
      path: '../public/fonts/Montserrat/static/Montserrat-Medium.ttf',
      style: 'normal',
      weight: '400'
    },
    {
      path: '../public/fonts/Montserrat/static/Montserrat-ExtraBold.ttf',
      style: 'normal',
      weight: '700'
    }
  ],
  variable: '--font-montserrat',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="bg-gray-900 text-white font-sans">
        {children}
      </body>
    </html>
  );
}
